# 1. Creating a NumPy array







# NumPy
* Numeric Python
* Open-source extension for working with arrays in Python
    * Remember: bais Python only uses lists (or tuples or sets or dicts), not arrays
* Arrays are of fixed size and contain only 1 datatype
* A array can be multidimensional
* Voobeelden
    * Rumikub
    * Schaken
    * Sudoku
    * Rubik's cube (GOATED)

# What's wrong with lists? 

* When you've used lists you've gotten used to very flexible programming
    * Add items, remove items, multiple datatypes, ...
* You'll feel reluctant to let this flexibility go and when doing 'normal' Python programming the difference between a list and np-array isn't that big
* But when you start doing AI oyu will feel the difference:
    * Dijkstra algorithm is a way finding the path through a maze
    * For this you need to try every single path there is
    * As a result, you go over the maze _a lot_
* But NumPy won't solve everything:
    * Arrays have one data type: you can't store name, age and sex together in a np-array 
    * The fix: Pandas dataframes
        * These are actually combined np-arrays

# Install and import NumPy

* Run the install command in a terminal window:
`pip install numpy `

* In Jupyter you must use a preceding **!**  to forec the code cell to be executed in a terminal window: 
`!pip install numpy`

* To import numpy we usually import it with a shorter name since it's used so much:
`import numpy as np`

In [2]:
# !pip install numpy 
import numpy as np

# Creating a NumPy array

* Via the function **array()** you create an array object.
* The first argument is a list or tuple. The number of elements in this list or tuple determines the **size** of the array.
* The second **optional argument** specifies the **type** of the elements.
    * If this argument is not given, Python determines the type itself.



In [3]:
# Create a 1d array from a list
list1 = [0,1,2,3,4,5]
arr1d = np.array(list1)


# Create a 2d array from a list of lists and datattype float
list2 = [[1,2,3], [4,5,6], [7,8,9]]
arr2d_float = np.array(list2, dtype='float')

print(type(arr1d))
print(arr1d)
print(type(arr2d_float))
print( arr2d_float)


<class 'numpy.ndarray'>
[0 1 2 3 4 5]
<class 'numpy.ndarray'>
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# Creating a NumPy array

* With the np methods ones(), zeros(), full(), random.random() an array of desired shape with initalized values can be created.

**np.ones((3,2))** -> zal een array returnen van 3 hoog en 2 breed gevuld met 1tjes
**np.zeros((3,2))** -> Zal een array returnen van 3 hoog en 2  breed gevuld met 0tjes
**np.random.random((3,2))** -> Zal een array return van 3 hoog en 2 breed gevuld met random getallen
**np.full((3,2),6)** -> array y: 3  & x: 2 gevuld met 6'en

* With the np method **arrange()** a sequence of numbers can be handled as a 1-dimensional array.

np.arange(5) -> [0, 1, 2, 3, 4] || np.arange(10,15) -> [10, 11, 12, 13, 14]




In [4]:
print("################################ \nones, random, zeros, full \n################################")

eentjes = np.ones((3,2))
random = np.random.random((4,4))
nullen = np.zeros((3,2))
volledig = np.full((3,2), 5)

print(eentjes)
print(random)
print(nullen)
print(volledig)

# Arange

print("################################ \nArange \n################################")

print(np.arange(5))
print(np.arange(10,15))



################################ 
ones, random, zeros, full 
################################
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0.06102237 0.84644694 0.34132475 0.18881227]
 [0.33729714 0.47895244 0.43229632 0.9993025 ]
 [0.05730119 0.54744773 0.67846392 0.49288657]
 [0.76554976 0.04172657 0.19446295 0.41750083]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[5 5]
 [5 5]
 [5 5]]
################################ 
Arange 
################################
[0 1 2 3 4]
[10 11 12 13 14]


# Properties of a NumPy array

* .ndim = 2
* .shape = (4,3)
* .shape[0] = 4
* .shape[1] = 3
* .dtype = int32
* .size= 12 -> 4*3

In [5]:
# Create a 2d array with 3 rows and 5 columns
# Initialized with random integers from 1 to 10
arr1d = np.random.randint(1,11,(5))
arr = np.random.randint(1,11,(3,5))

print(arr)

# ndim
print(f'Num dimensions: {arr.ndim}')

# Shape 
print(f'Shape: {arr.shape}')

# Number of rows
print(f'Number of rows: {arr.shape[0]}')

# Number of columns
print(f'Number of columns: {arr.shape[1]}')

# datatype
print(f'Datatype: {arr.dtype}')

# size
print(f'Size: {arr.size} => 3 * 5')

[[ 8  9  7  1  7]
 [10 10  1  8  1]
 [ 2  6  7  7  3]]
Num dimensions: 2
Shape: (3, 5)
Number of rows: 3
Number of columns: 5
Datatype: int32
Size: 15 => 3 * 5


#Arithmetic operations

* There are often cases when you want to carry out an operation between an array and a single number (you can also call this an operation between a vector and a scalar). 
* Say, for example, an array represents the distance in miles, and you want to convert it to kilometers. You can simply say data * 1.6

[1, 2] * 1.6 => [1.6, 3.2]

* The multiplication happens with every cell => that concept is **broadcasting**

* You can add and multiply matrices using arithmetic operators (+-*/) if the two matrices are the same size. NumPy handles those as position-wise operations.

* NumPy broadcasting is a mechanism that enable elemnt-wise operations on arrays of different shapes by automatically "strecthing" the smaller array along the appropriate dimensions to match the larger array's shape, allw ithout creating unnecessary copies of the data.

In [26]:
data = np.arange(1,4)
powers_of_ten = 10 ** np.arange(0, 6)
power_of_ten_arr = powers_of_ten.reshape(3,2)
print(power_of_ten_arr)
print(data)
data.dot(power_of_ten_arr)


[[     1     10]
 [   100   1000]
 [ 10000 100000]]
[1 2 3]


array([ 30201, 302010])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)